require("resources/sessions/sessions-apis");
require("resources/proxy/proxy-routes.js");
require("resources/users/users-apis");
require("resources/service-categories/service-categories-routes");
require("resources/admin-control/admin-control-apis");
require("resources/ideas/ideas-apis.js")
require('resources/services/services-routes.js');
require("resources/tags/tags-api.js");
require('resources/aws/routes-aws.js');
require("resources/article/article-api.js");
require('resources/zones/zones-apis.js');
require("resources/organisation/organisation-apis.js");
